version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo-wishlist
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: wishlist-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/wishlists

volumes:
  mongo_data: